name = "cloudflare"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "cloudflare"
database_id = "772c7f599d5164b11cc5c"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cloudflare"

[ai]
binding = "AI"
